### ISSUE TITLE
USER STORY: DEPLOYMENT

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#16]
As a **Developer** I can **deploy the website early**, so I can **avoid additional stress and technical issues in the moment of the project submission**

### Acceptance criteria:

 The project must be deployed to Heroku
- The project must be connected to the 3rd party database like ElephantSQL
- The code must be stored on GitHub to be evaluated by the assessor
- The project must be displayed through GitHub app

### Tasks:

- [x] Creating workspace with Gitpod
- [x] Connecting Github to Heroku
- [x] Installing dependencies
- [x] Setting up the enviroment variables
- [x] Connecting ElephantSQL
- [x] Ensuring that app is displaying properly on Heroku
- [x] Connect to Cloudinary to Django and Heroku

**Comment by TulaUnogi** [comment]
When trying to deploy to Heroku for the first time I got a collectstatic error which resulted  in the failure of a deployment.
After realising that I forgot to set up the static files and fixing that mistake I managed to deploy the app successfully.

**Comment by TulaUnogi** [comment]
(From 'finished' back to 'in progress')
As advised by my mentor Narender I should connect Cloudinary for hosting static files

**Comment by TulaUnogi** [comment]
After connecting to Cloudinary Heroku build failed, disabled collectstatic temporarily and build was successful
