### ISSUE TITLE
USER STORY: ADMIN PANEL

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#17]
As a **Business Manager** I can **access the admin panel**, so I can **see and update all of the informations**.

### Acceptance criteria

- Must be able to log in as a backend's admin
- Must be able to add, edit, save and delete the content

### Tasks

- [x] Create a SuperUser  in terminal (backend)
- [x] Assign an admin link
- [x] Check if Admin is able to successfully log in and make changes
