### ISSUE TITLE
USER STORY: CREATE AN ACCOUNT

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#18]
As a **User** I can **create an account**, so I can **make and manage my bookings**

### Acceptance criteria

- User must provide all of their relevant data to be able to make a booking
- Blank fields at the login and registration page should not be left empty to get accepted
- User should be able to log in and out after creating their account
- User should be able to access their profile page in relation to reviewing and updating their  account
- User should be able to delete their account

### Tasks

- [x] Creating the backend of the profile
- [x] Add a template of the website with appropriate link
- [x] Style the profile page using bootstrap and css
