### ISSUE TITLE
USER STORY: ABOUT US

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#19]
As a **User** I can **easily access "About" page**, so I can **find out more about the business**

### Acceptance criteria

- The "About" button must be easy to find on the homepage
- The "About" button must be able to redirect the user to the "/about" subpage
- The "/about" subpage must include important information, like: menu, list of cats, address and contact details

### Tasks

- [x] Design a homepage that includes the appropriately sized "About" button with good contrast level for readability
- [x] Assign a link to a button
- [x] Design an "About" subpage
- [x] Design a set of 3 cards that would display information about Menu, Cats and Contact after being clicked by User
- [x] Allow User to dismiss displayed information by including a "close" button
