### ISSUE TITLE
USER STORY: NAVBAR AND FOOTER

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#20]
As a **User** I can **see a navbar and footer present on every page**, so I can **easily navigate through website and access relevant links**

### Acceptance criteria

- Website must include navbar and footer on every page
- Navbar must include relevant working links to other subpages, e.g. "Home", "About", "Sign In", "Sign Out", "Register"
- Footer must include working links to social media and short copyrights note

### Tasks

- [x] Design a base template that includes navbar and footer to be extended with the use of other subpage templates
- [x] Assign urls and connect their paths to templates to ensure functionality of the links
- [x] Use icons to represent social media platforms in footer
