### ISSUE TITLE
USER STORY: TABLE BOOKING

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#21]
As a **Customer** I can **book a table**, so I can **visit a café without a concern that my chosen seat will be taken**

### Acceptance criteria

- User must have an existing account to be able to log in to the booking system
- User cannot access the booking system without logging in
- User's profile must include all of the required information for the booking
- Admin must be able to see the booking information to approve or decline it (backend)
- User must be able to see if his reservation has been confirmed

### Tasks

- [x] Creating table booking model as a backend
- [x] Creating a frontend booking form 
- [x] Adding booking details to User's profile after the form has been submitted
- [x] Adding a status confirmation to the booking for User to see
- [x] Add edit booking model

### Restrictions to implement

- [ ] Only one booking per day (prevents multiple bookings)
- [ ] Bookings open from 2 hours before opening up to 1 hour before closing
- [ ] Bookings only available from the current date onwards (up to 1 day in the future)
- [ ] One customer can add more than one table to the booking (max 3 tables to prevent booking of the whole café for 1 customer)

**Comment by TulaUnogi** [comment]
Note to self:
Should add restrictions like:
- Only one booking per day (prevents multiple bookings)
- Bookings open from 2 hours before opening up to 1 hour before closing
- No time travelling: bookings only available from the current date onwards (up to 1 day in the future)
- One customer can add more than one table to the booking (max 3 tables to prevent booking of the whole café for 1 customer)

Should add edit booking model

**Comment by TulaUnogi** [comment]
Currently facing an error in booking form: didn't return an HttpResponse object. It returned None instead.

**Comment by TulaUnogi** [comment]
Edit booking currently works partially... You can only edit one booking before the error

**Comment by TulaUnogi** [comment]
Edit booking fixed
