### ISSUE TITLE
USER STORY: DELETING PROFILE

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#23]
As a **User** I can **delete my profile**, so **it will be removed from a database**

### Acceptance criteria

- User must have an existing account and be logged in to delete it
- User must be able to see the delete button in order to use it
- User must confirm his decision on deleting their account by clicking on modal's button

### Tasks

- [x] Add "delete" CRUD logic to the User's profile
- [x] Add the "Delete" button to frontend for the User
- [x] Style the "Delete" button to stand out with warning colours which may prevent User from accidental click
- [x] Add and style the confirmation pop up modal
