### ISSUE TITLE
USER STORY: CAT CAROUSEL

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#24]
As a **User** I can **click on "Our Cats" card's button**, so I can **see the pictures of the cats displayed in form of carousel**

### Acceptance criteria

- The cat card must include the functional button
- The button must trigger the pop up modal after being clicked by User
- The modal must have embedded the bootstrap carousel containing pictures of the cats with their names and short description
- The modal must include the "close" button for the User to dismiss

### Tasks

- [x] Create and style the card using html, css and bootstrap
- [x] Add a javascript function to trigger the onclick event to the button
- [x] Embed the bootstrap carousel in card's html and style it with css
- [ ] Add the pictures with description to the carousel's code
- [x] Add and style the "close button"

**Comment by TulaUnogi** [comment]
Descriptions not necessary at this point, left for the future
