### ISSUE TITLE
USER STORY: GOOGLE MAPS

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#25]
As a **Customer** I can **see embedded Google Maps on the contact page**, so I can **find directions to the café**

### Acceptance criteria

- Contact details must be embedded in a modal triggered by User after clicking the button on a "Contact Us" card
- Contact modal must contain an iframe element with a link to exact location of the café
- The iframe element must be styled appropriately to fit the content of the website
- The iframe element should be accessible for screen readers
- Full address and contact details should be present alongside the map

### Tasks

- [x] Create and style the "Contact Us" card and modal
- [x] Add an Google Maps iframe element to the modal
- [x] Style an iframe using bootstrap classes
- [x] Add an aria-label attribute to the iframe
- [x] Add address and contact details
