### ISSUE TITLE
USER STORY: MENU

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#26]
As a **Customer** I can **see the Menu**, so I can **get information on products served in a café**

### Acceptance criteria

- A "Menu" card must be present on "/about" subpage
- A button must trigger a pop up modal with menu after being clicked by User
- The modal must include a "close" button for the User to dismiss

### Tasks

- [x] Add and style a "Menu" card to "/about"
- [x] Add onclick javascript function to the button to activate the modal with picture of the menu
- [x] Add close button to the modal
