### ISSUE TITLE
USER STORY:  BOOKING CANCELLATION

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#27]
As a **Customer** I can **cancel my booking**, so I can **inform the café about my absence in advance**

### Acceptance criteria

- User must have an existing account to be able to log in to the booking system
- User cannot access the booking system without logging in
- User must have an active booking assigned to their profile
- User must confirm cancellation on a pop up modal
- Admin must get a notification on User's cancellation

### Tasks

- [x] Add "cancellation" CRUD logic to the User's booking model
- [x] Add the "Cancel Booking" button to frontend for the User
- [ ] Add a cancellation confirmation popup window
- [ ] Add  "Is cancelled?" field on the backend site for Admin to see in case of cancellation

**Comment by TulaUnogi** [comment]
Note to self: If time allows create a custom admin  page to allow pop up messages when User makes cancellation

Also, as I talked with my mentor we decided that on the admin site is good to include "Is cancelled" field instead just a comment

**Comment by TulaUnogi** [comment]
Currenntly only standard deleting available
