### ISSUE TITLE
Stock management

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#29]
As a **Business Manager** I can **access the admin panel**, so I can **see and update all of the items in the shop**.

### Acceptance criteria

- Must be able to log in as an admin
- Admin must be able to add an item for sale
- Admin must be able to update an item including it's picture, price and description
- Admin must be able to delete an item from the shop.

### Tasks

- [] Create a SuperUser  in terminal (backend)
- [] Assign a stock management link
- [] Enable adding items to shop
- [] Enable editing items
- [] Enable deleting items
- [] Test if Admin is able to successfully log in and make changes
