### ISSUE TITLE
README: Update Agile Development module 

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/cat-beans-cafe#7]
### Write the up-to-date content for the Agile Development module.

- [x] Write an overview
- [x] Describe the User Stories
- [x] Add links to Kanban and Stories
